name: Hackathon-Frontend-Build-Deploy

on: push

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test
        env:
          CI: false
        
      - name: Generate build
        run: npm run build
        env:
          CI: false